### ISSUE TITLE
1.0.6 version doesn't work on windows and linux

### ISSUE THREAD

**Issue by luzz94** [nesnes/teleplot#1]
I've been using teleplot for a couple of months now, and I'm doing so well with them that I can't get by without them.

I wanted to report that version 1.0.6 does not work in either linux (ubuntu 20.04) or Windows 10/11

From Ubuntu 20.04 launching VS Code extension debugging I have:
`
...
activating extension
...
starting language server
...
null

(node:6035) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
...
`

and moreover it prompt me:

`The terminal process "/usr/bin/bash '-c', 'npm run watch'" failed to launch (exit code: 127).`

Same for Win and Ubuntu the GUI is available but i cannot open any serial port.

1.0.5 works only on Windows and on ubuntu 20.04 the button in the lower left corner doesn't appear either (and the same for earlier versions).

I hope it helps and it can be easily solvable

bye

**Comment by nesnes** [comment]
Hi, you are using the VSCode extension for Teleplot which is available on the following repo: https://github.com/nesnes/teleplot-vscode

I didn’t yet found a way to merge the two repos and avoid code duplication.

About your issue, it should have been fixed in the 1.0.7 version of the extension, can you confirm?

**Comment by luzz94** [comment]
Thanks you very much!

Sorry for the confusion with the repo...

I confirm you that with Teleplot 1.0.7 and VSCode 1.69.0 both on Window (10 and 11) and Ubuntu 20.04 seems work perfectly! 

in order to finish the job i was able to come back to VSCode 1.65.0 and Teleplot 1.0.5 on windows since i was using Teleplot to tune a PID controller.
