### ISSUE TITLE
simple question on changing port to listen to

### ISSUE THREAD

**Issue by bwanaaa** [nesnes/teleplot#16]
By default teleplot listens on port 47269. But I want to plot telemetry from a flight simulator, DigitalCombatSimulator  (DCS). It sends its telemetry out on port 34380. Is there a way to capture and plot DCS telemetry with teleplot?

**Comment by nesnes** [comment]
Hi,

While I already played it, I'm not familiar with DCS telemetry, but I'm sure that changing the port won't be the solution, as teleplot will expect telemetry to be formated in a specific way for this to work.

Having said so, I've just read a few tutorials on DCS telemetry system and it seems that we can give it a LUA script (Export.lua) and do whatever we want  in lua. This means that we can send teleplot-formted messages from this script!

To give you a full answer, I decided to re-download DCS and write a few line of LUA, to see how the telemetry works. And in no-tomie, I managed to send Teleplot telemetry from DCS! 🎉 ✈️ 📈 

Here is the `Export.lua` script I used and saved in `C:\Users\MyUserName\Saved Games\DCS\Scripts` folder.
```lua
-- Sample script to export DCS world telemetry to Teleplot

-- Import socket lib
package.path  = package.path..";.\\LuaSocket\\?.lua"
package.cpath = package.cpath..";.\\LuaSocket\\?.dll"
socket = require("socket")

-- Setup Teleplot UDP socket
udp = socket.udp()
teleplotAddr = "127.0.0.1"
teleplotPort = 47269
udp:settimeout(0)
udp:setoption('reuseaddr',true)

-- Implement DCS Export hook functions
function LuaExportStart()
end

function LuaExportBeforeNextFrame()
end

function LuaExportAfterNextFrame()
end

function LuaExportStop()
udp:close()
end

function LuaExportActivityNextEvent(t)
-- Get simulation time in milliseconds
local time = LoGetModelTime() * 1000

-- Send Multiple telemetry values to teleplot
local altASL = LoGetAltitudeAboveSeaLevel()
udp:sendto(string.format("AltitudeAboveSeaLevel:%.0f:%.2f§feet", time, altASL), teleplotAddr, teleplotPort)

local altAGL = LoGetAltitudeAboveGroundLevel()
udp:sendto(string.format("AltitudeAboveGroundLevel:%.0f:%.2f§feet", time, altAGL), teleplotAddr, teleplotPort)

local speedI = LoGetIndicatedAirSpeed()
udp:sendto(string.format("IndicatedAirSpeed:%.0f:%.2f§knots", time, speedI), teleplotAddr, teleplotPort)

local speedT = LoGetTrueAirSpeed()
udp:sendto(string.format("TrueAirSpeed:%.0f:%.2f§knots", time, speedT), teleplotAddr, teleplotPort)

local aoa = LoGetAngleOfAttack()
udp:sendto(string.format("AngleOfAttack:%.0f:%.2f§degrees", time, aoa), teleplotAddr, teleplotPort)

local accel = LoGetAccelerationUnits()
udp:sendto(string.format("AccelerationUnitsX:%.0f:%.2f§G", time, accel.x), teleplotAddr, teleplotPort)
udp:sendto(string.format("AccelerationUnitsY:%.0f:%.2f§G", time, accel.y), teleplotAddr, teleplotPort)
udp:sendto(string.format("AccelerationUnitsZ:%.0f:%.2f§G", time, accel.z), teleplotAddr, teleplotPort)

local speedVertical = LoGetVerticalVelocity()
udp:sendto(string.format("VerticalVelocity:%.0f:%.2f§feet/sec", time, speedVertical), teleplotAddr, teleplotPort)

local pitch, bank, yaw = LoGetADIPitchBankYaw()
udp:sendto(string.format("Pitch:%.0f:%.2f§degrees", time, math.deg(pitch)), teleplotAddr, teleplotPort)
udp:sendto(string.format("Bank:%.0f:%.2f§degrees", time, math.deg(bank)), teleplotAddr, teleplotPort)
udp:sendto(string.format("Yaw:%.0f:%.2f§degrees", time, math.deg(yaw)), teleplotAddr, teleplotPort)
udp:sendto(string.format("3D|ADIPitchBankYaw:%.0f:S:cube:W:1:D:2:H:0.5:R:%.2f:0:%.2f", time, pitch, -bank ) , teleplotAddr, teleplotPort)

local magneticYaw = LoGetMagneticYaw()
udp:sendto(string.format("MagneticYaw:%.0f:%.2f§degrees", time, math.deg(magneticYaw)), teleplotAddr, teleplotPort)


return t+0.1
end
```
Launching Teleplot (with one of the numerous ways listed in the [readme](https://github.com/nesnes/teleplot/blob/main/README.md) ) and starting a DCS flight, I managed to get the following output:

![image](https://user-images.githubusercontent.com/9192862/218890182-c84d55ca-32cc-4c82-b1c0-0fff67c711a9.png)

Now have fun!

**Comment by bwanaaa** [comment]
Thank you SO MUCH!

**Comment by bwanaaa** [comment]
I made the export lua a little neater by putting your code in a text file named TelePORT.lua which is put into the scripts folder in Saved Games-> DCS openbeta->Scripts. And then adding this line to the export.lua
local telePORTlfs=require('lfs');dofile(telePORTlfs.writedir()..'Scripts/TelePORT.lua')

**Comment by bwanaaa** [comment]
thanks again
