### ISSUE TITLE
Dark Colour-scheme

### ISSUE THREAD

**Issue by Axel-ex** [nesnes/teleplot#19]
Thank you very much for this tool which works really well and is really intuitive! I wanted to know if you could potentially implement a dark colour-scheme? Thanks a lot

**Comment by nesnes** [comment]
Hi,
It's now implemented!

Whether you launch it locally or from the VSCode extension, you'll find a dedicated button at the top-right of the window.

(Only the website didn't received the update yet)

**Comment by Axel-ex** [comment]
Hi,

Wow amazing, thank you for taking the request into consideration and thanks
for your time! Can’t wait to try it!

Axel

**Comment by mhaberler** [comment]
very nice!

can I suggest to adapt the axis values from dark to white in dark mode?
I guess the grid needs more contrast too
![Bildschirmfoto 2023-08-17 um 18 37 01](https://github.com/nesnes/teleplot/assets/901479/297eb8d8-4ad4-415c-8637-d452759487fe)
![Bildschirmfoto 2023-08-17 um 18 37 23](https://github.com/nesnes/teleplot/assets/901479/310b8c37-f415-4789-8586-2099204dc323)

**Comment by bit4man** [comment]
> Hi, It's now implemented!
> 
> Whether you launch it locally or from the VSCode extension, you'll find a dedicated button at the top-right of the window.
> 
> (Only the website didn't received the update yet)

I just discovered teleplot last week and have eagerly had not just fun but getting some useful data using it.  But the dark theme while there, isn't really working.  It's dark yes, but a lot of the fonts are still written in black.  See the two screendumps.  You cannot see the max/min etc, it's very hard to see the axis labels, the guide lines are almost impossible to see etc.  I don't mind switching to the light mode for the period I need to study the graphs/output but the dark-mode seems to be missing some functionality?

Thanks for the tool though - bad colors or not, it's really useful and extremely easy to use.


![Screenshot from 2023-12-03 14-56-05](https://github.com/nesnes/teleplot/assets/1713562/e502d297-55d2-490d-b7f8-f8f1eb858e7a)
![Screenshot from 2023-12-03 14-56-19](https://github.com/nesnes/teleplot/assets/1713562/49a2d0f0-1b78-4451-911b-37fa9e2bbe40)

**Comment by nesnes** [comment]
I've published an update of the vscode extension with a tradeoff on axes color that should make them visible in both color modes.
(I'll have more work to do to update the website part)
