### ISSUE TITLE
Feature Request: Customize Decimal Separator for CSV Exports

### ISSUE THREAD

**Issue by UGHyodo** [nesnes/teleplot#21]
Firstly, I want to express my gratitude for the exceptional Teleplot extension for VSCode. As someone who was seeking a way to replicate the functionality of the Arduino IDE's Serial Plotter in VSCode, this extension has proven to be an ideal solution. It is remarkably intuitive and user-friendly.

If I may make one humble request, it would be to inquire if it's possible to add an option to customize the decimal separator when exporting a session to a CSV file. In East Asian countries, when data is opened in Excel, a numeric value like "12,345" is interpreted as "12.345*10^3." Therefore, it would be greatly appreciated if CSV data exports could use "." as the decimal separator to avoid this issue.

Once again, thank you for this fantastic extension, and I look forward to your consideration.

**Comment by nesnes** [comment]
Hi, thanks for your kind words!

I've just published a new version (1.1.3) of the extension that should allow you to select the decimal separator and the cell separator when exporting in csv.

Don't hesitate to share your feedback after testing it!

**Comment by UGHyodo** [comment]
Hi,

Thank you so much for your prompt response and for implementing the feature! I truly appreciate your dedication to improving the Teleplot extension.

I've just updated version 1.1.3 and tested the new customization options for the decimal separator and cell separator when exporting in CSV. It works perfectly and addresses my previous concern thoroughly. This is a significant enhancement that will make the extension even more versatile for users worldwide.

I'm looking forward to using Teleplot with these new options, and I'll definitely share any feedback if I come across any issues or have suggestions for further improvements.

Once again, thank you for your fantastic work and your commitment to making Teleplot even better.

Best regards.
