### ISSUE TITLE
flag clr

### ISSUE THREAD

**Issue by micheldufresne** [nesnes/teleplot#30]
Hello,

Thank you for your Teleplot.
I’m using teleplot extension with vscode, i want to clear the screen after send 100 points.
Documentation says " Using clr flag when sending a telemetry will clear the previous values."
Then i tried this in the loop :
` Serial.printf(">U:|clr\n"); //clear teleplot screen

  for (int i=0 ; i<nbvaleurs ; i++)
  {
    Serial.printf(">U:%u:%u|xy\n",i,courant[i]); //plot new points
  } `
First line has no effect, what is the good syntaxe ?
Thank you sir for your help.

Michel

**Comment by nesnes** [comment]
Hi,
What happens is that you need to send a valid telemetry, along with the clr flag. ">U:0:0|xy,clr"
Notice that the value sent with the clr flag will not be cleared, so what you could do is to add "clr" in your for loop, only when i==0
